### ISSUE TITLE
Question on the GraphData

### ISSUE THREAD

**Issue by BooneAllred** [kno20205/pathpal-indoor-navigation#2]
I am curious how you're generating the graphdata to be used in this app. Mainly the connection between points, are you generating those connections or are you entering them manually? Also when you create the points are you just creating the points and no connections between them in your vector program?

**Comment by KnotzerIO** [comment]
Thank you for your interest! The process is indeed quite complex. Currently, I manually draw the points in a vector editing software and export them as an SVG file. I then use a script to convert the coordinates from the SVG to JSON format. The connections between points are manually defined afterwards. I planed to integrate a custom map editor into the application to simplify this process, but due to other ongoing projects, this feature won't be available in the near future.
