### ISSUE TITLE
Updating the map

### ISSUE THREAD

**Issue by adjebbar** [kno20205/pathpal-indoor-navigation#4]
Hey,

I would like to change the map (plan) with mine. How can I proceede please ?

Regards.

**Comment by KnotzerIO** [comment]
The process is indeed quite complex. Currently, I manually draw the points in a vector editing software and export them as an SVG file. I then use a script to convert the coordinates from the SVG to JSON format. The connections between points are manually defined afterwards. I planed to integrate a custom map editor into the application to simplify this process, but due to other ongoing projects, this feature won't be available in the near future.

**Comment by KrishEnacton** [comment]
@KnotzerIO Do you have any video tutorial of doing this steps or is there any future plan to integrate map editor tool in this project?

**Comment by KnotzerIO** [comment]
No, I don't have a video tutorial and don't plan to make one. However, why not check out my new project that I’m currently working on with my colleagues? It’s called [OpenIndoorMaps](https://github.com/openindoormap/openindoormaps), and I’ve mentioned it in this project's sidebar and README.  

The project is currently in development, but I believe there will be a minimal viable product in a few months. Give it a star to stay up-to-date, and consider contributing to help shape its future!
